FROM golang:1.21.3

WORKDIR /app

ARG DATA_DIR

VOLUME [ ${DATA_DIR} ]

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./

ADD web/ ./web/

RUN go build -o /my_app

CMD [ "/my_app" ] 